# Часть 2: алгоритмическая задача

Для решения была выбрана задача о рюкзаке: есть рюкзак определенной вместимости. Есть конечное количество вещей разного веса и ценности, которые в этот рюкзак можно положить, но поместятся не все вещи. Цель: найти такой набор вещей, который можно сложить в рюкзак, чтобы при ограниченной вместимости рюкзака была достигнута максимально возможная его ценность.

In [3]:
!pip install pygmo

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 11.5 MB 7.8 MB/s 


In [4]:
import math
import pygmo as pg
import numpy as np
from matplotlib import pyplot as plt
from matplotlib import animation
from matplotlib import rc
from matplotlib import colors as cm

In [5]:
class Rucksack():
  def __init__(self, weight, cost, limit_weight):
    self.dim = len(cost)
    self.weight = weight
    self.cost = cost
    self.limit_weight = limit_weight

  def get_bounds(self):
    return (np.full((self.dim,), 0), np.full((self.dim,), 1))

  def fitness(self, x):
    result, limitation = np.zeros((1,)), np.zeros((1,))
    for i in range(self.dim):
      round_x = round(x[i])
      result[0] += round_x * self.cost[i]
      limitation[0] += round_x * self.weight[i]
    if (limitation[0] > self.limit_weight):
      return np.zeros((1,))
    else:
      return -result

In [6]:
cost = [17, 17, 17, 30, 30, 30, 75, 75, 75] #массив значений ценности вещей
weight = [1.5, 1.5, 1.5, 2.5, 2.5, 2.5, 6, 6, 6] #массив значений занимаемого места
limit_weight = 20 #ограничение по вместимости
res = np.zeros([9, 8])
for i in range(1, 10):
  for j in range(2, 10):
      algo = pg.algorithm(pg.bee_colony(gen = i))
      prob = pg.problem(Rucksack(weight, cost, limit_weight))
      pop = pg.population(prob, j)
      pop = algo.evolve(pop)
      res[i-1][j-2] = -pop.champion_f[0]

print("Список лучших\n", res)

Список лучших
 [[182. 214. 201. 214. 240. 231. 244. 231.]
 [199. 214. 199. 197. 244. 244. 244. 244.]
 [227. 240. 244. 240. 242. 201. 214. 244.]
 [227. 227. 244. 231. 244. 231. 244. 244.]
 [227. 227. 244. 231. 242. 242. 244. 244.]
 [231. 244. 231. 214. 244. 244. 244. 244.]
 [186. 240. 244. 244. 244. 244. 244. 244.]
 [244. 231. 244. 244. 244. 244. 244. 244.]
 [240. 242. 240. 244. 244. 244. 240. 244.]]
