# Numpy100

*   Выдано заданий: (39 / 100)
*   Выполнено заданий: (39 / 39)
*   Выполнео заданий всего: (39 / 100)


### 1. Import the numpy package under the name np (★☆☆)

In [ ]:
import numpy as np

### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print("Версия: ", np.version.version, "\nКонфигурация: ")
np.show_config()

Версия:  1.21.6 
Конфигурация: 
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,

### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
vector = np.zeros(10)
vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 4. How to find the memory size of any array (★☆☆)

In [ ]:
arr = np.ones([2, 3])
print("Elements count: ", arr.size, "\nBytes: ", arr.itemsize * arr.size)

Elements count:  6 
Bytes:  48


### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
#python -c "import numpy; numpy.info(numpy.add)"

### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
vector = np.zeros(10)
vector[5] = 1
vector

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
vector = np.arange(10, 50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
vector = vector[::-1]
vector

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
matrix = np.arange(9)
matrix.shape = 3, 3
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
vector = np.array([1,2,0,0,4,0]).nonzero()
vector

(array([0, 1, 4]),)

### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
matrix = np.eye(3)
matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
array = np.random.random((3, 3, 3))
array

array([[[0.01067912, 0.08560493, 0.08291919],
        [0.28235   , 0.49952964, 0.44526742],
        [0.77406002, 0.96123385, 0.42222781]],

       [[0.75441878, 0.26677654, 0.12996555],
        [0.21758155, 0.47827558, 0.41789411],
        [0.41126144, 0.64220387, 0.35038418]],

       [[0.92150747, 0.14016206, 0.50483088],
        [0.48111082, 0.30735431, 0.08915736],
        [0.61313201, 0.06432148, 0.37676391]]])

### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
array = np.random.random((10, 10))
print(array.max(), array.min())

0.997386985102289 0.001499048784727619


### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
vector = np.random.random(30)
vector.mean()

0.48875348154898324

### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
matrix = np.ones([5, 5])
matrix[1:-1, 1:-1] = 0
matrix

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
matrix = np.pad(matrix, pad_width=1, mode='constant', constant_values=0)
matrix

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

### 17. What is the result of the following expression? (★☆☆)

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1

In [ ]:
0 * np.nan #np.nan
np.nan == np.nan #False
np.inf > np.nan #False
np.nan - np.nan #nan
np.nan in set([np.nan]) #True
0.3 == 3 * 0.1 #False

False

### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
matrix = np.diag(range(1, 5), k=-1)
matrix

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
matrix = np.zeros([8, 8])
matrix[::2, ::2] = 1
matrix[1::2, 1::2] = 1
matrix

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
np.unravel_index(100, [6, 7, 8])

(1, 5, 4)

### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
matrix = np.tile(([1, 0], [0, 1]), (4, 4))
matrix

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
matrix = np.random.random([5, 5])
matrix = (matrix - matrix.mean()) / matrix.std()
matrix

array([[-1.34838209,  0.05534107, -0.20981547, -1.62580384, -0.08959229],
       [-1.61496852, -1.13987183,  1.20339112, -0.11105964,  1.03810664],
       [-1.62813271, -0.23769599,  0.96489645,  0.88249767,  1.37930551],
       [-0.45483572,  1.31554363,  0.09586994,  0.73807321, -0.69671669],
       [-0.87366304,  0.5751203 , -0.70363115,  1.4192458 ,  1.06677764]])

### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color = np.dtype([("r", np.ubyte, 1), ("g", np.ubyte, 1), ("b", np.ubyte, 1)])
color

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """Entry point for launching an IPython kernel.


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1')])

### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
m1 = np.random.random([5, 3])
m2 = np.random.random([3, 2])
m1 @ m2

array([[0.50564136, 0.69810369],
       [0.76010391, 0.74490999],
       [1.35605956, 1.21708221],
       [1.031379  , 0.6369577 ],
       [1.17766124, 1.27132686]])

### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
array = np.arange(10)
array[4:8] *= -1
array

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

### 26. What is the output of the following script? (★☆☆)

print(sum(range(5),-1))

In [ ]:
print(sum(range(5),-1)) #0 + 1 + 2 + 3 + 4

10


### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

Z**Z

2 << Z >> 2

Z <- Z

1j*Z

Z/1/1

Z<Z>Z

In [ ]:
#Is legal:
#Z**Z
#2 << Z >> 2
#Z <- Z
#1j*Z
#Z/1/1

### 28. What are the result of the following expressions? (★☆☆)

np.array(0) / np.array(0)

np.array(0) // np.array(0)

np.array([np.nan]).astype(int).astype(float)

In [ ]:
np.array(0) / np.array(0) #error
np.array(0) // np.array(0) #0
np.array([np.nan]).astype(int).astype(float) #numpy.ndarray([float])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-9.22337204e+18])

### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
a = np.array([0.58, 0.333, 0.237])
np.round(a, 1)

array([0.6, 0.3, 0.2])

### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
a = np.array([0, 2, 3, 4])
b = np.array([1, 2, 3, 4, 5])
np.intersect1d(a, b)

array([2, 3, 4])

### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
np.seterr(all="ignore")

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

### 32. Is the following expressions true? (★☆☆)

np.sqrt(-1) == np.emath.sqrt(-1)

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
today = np.Datetime64('today')
yesterday = today - np.timedelta64('1')
tomorrow = today + np.timedelta64('1')
print("Сегодня: ", today, "\nВчера: ", yesterday, "\nЗавтра: ", tomorrow)

Сегодня:  2022-10-25 
Вчера:  2022-10-24 
Завтра:  2022-10-26


### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.eye(2)
B = np.eye(2)
np.add(A, B, out=B)
np.divide(A, -2, out=A)
np.multiply(A, B, out=A)
A

array([[-1., -0.],
       [-0., -1.]])

### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
array = np.random.uniform(0, 10, 10)
print(array // 1)
print(np.floor(array))
print(array.astype(int))
print(np.trunc(array))

[6. 5. 1. 8. 3. 6. 2. 1. 6. 3.]
[6. 5. 1. 8. 3. 6. 2. 1. 6. 3.]
[6 5 1 8 3 6 2 1 6 3]
[6. 5. 1. 8. 3. 6. 2. 1. 6. 3.]


### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
matrix = np.zeros([5, 5]) + np.arange(5)
matrix

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generate():
    for x in range(10):
        yield x
        
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
vector = np.linspace(0, 1, 11, endpoint=False)[1:]
vector

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

### 40. Create a random vector of size 10 and sort it (★★☆)

### 41. How to sum a small array faster than np.sum? (★★☆)

### 42. Consider two random array A and B, check if they are equal (★★☆)

### 43. Make an array immutable (read-only) (★★☆)

### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

### 46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)

### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

### 49. How to print all the values of an array? (★★☆)

### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

### 54. How to read the following file? (★★☆)

1, 2, 3, 4, 5

6,  ,  , 7, 8

 ,  , 9,10,11

### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

### 56. Generate a generic 2D Gaussian-like array (★★☆)

### 57. How to randomly place p elements in a 2D array? (★★☆)

### 58. Subtract the mean of each row of a matrix (★★☆)

### 59. How to sort an array by the nth column? (★★☆)

### 60. How to tell if a given 2D array has null columns? (★★☆)

### 61. Find the nearest value from a given value in an array (★★☆)

### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

### 63. Create an array class that has a name attribute (★★☆)

### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★)

### 69. How to get the diagonal of a dot product? (★★★)

### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

### 72. How to swap two rows of an array? (★★★)

### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)

### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

### 75. How to compute averages using a sliding window over an array? (★★★)

### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) (★★★)

### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

### 82. Compute a matrix rank (★★★)

### 83. How to find the most frequent value in an array?

### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

### 88. How to implement the Game of Life using numpy arrays? (★★★)

### 89. How to get the n largest values of an array (★★★)

### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

### 91. How to create a record array from a regular array? (★★★)

### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

### 95. Convert a vector of ints into a matrix binary representation (★★★)

### 96. Given a two dimensional array, how to extract unique rows? (★★★)

### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)